# Gabriel quiver of the local correspondent B_0(kN), N = N_Sz(8)(P).
#
# The seven simple kN-modules are indexed by the characters of N/P, with
# indices in Z/7Z.  The radical generators have C7-weights 1, 2, and 4.
# This is the quiver skeleton; the reproducible relation set is generated by
# scripts/build_local_from_group.g using AlgebraAsQuiverAlgebra.

LocalQuiver := function()
    local arrows, i;
    arrows := [];
    for i in [0..6] do
        Add(arrows, [i+1, ((i+1) mod 7)+1, Concatenation("x", String(i))]);
        Add(arrows, [i+1, ((i+2) mod 7)+1, Concatenation("y", String(i))]);
        Add(arrows, [i+1, ((i+4) mod 7)+1, Concatenation("z", String(i))]);
    od;
    return Quiver(7, arrows);
end;

Q_B_skeleton := LocalQuiver();
